name: Core
description: 'Provides core components required by other features.'
type: module
core: 8.x
dependencies:
  - block
  - block_content
  - contact
  - file
  - menu_link_content
  - node
  - shortcut
  - taxonomy
  - tour
  - user
package: 'Initial Site Config'
